package com.application.Exercice.model;

import java.util.ArrayList;
import java.util.Collection;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
// Getters ans setters are generated by @Data
@AllArgsConstructor
// Constructor with all fields
@NoArgsConstructor
// Constructor with no fields
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    private String name;
    private String username;
    private String password;

    @ManyToMany(fetch = FetchType.EAGER)
    // fetch = FetchType.EAGER : pour charger les roles au moment du chragement de
    // l'utilisateur
    private Collection<Role> roles = new ArrayList<>();

}
